services:
    park.twig.computer_status_extension:
        class: ParkBundle\Twig\ComputerExtension
        tags:
            - { name: twig.extension }

    park.computerManager:
        class: ParkBundle\Services\ComputerManager
        arguments: ["@doctrine"]

    park.calculator:
        class: ParkBundle\Services\Calculator

