park :
    resource: "@ParkBundle/Controller/"
    type: annotation
    prefix:   /park

#test:
#    resource: "@ParkBundle/Controller/"
#    type:     annotation
#    prefix:   /test

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

