services:
    app.security.user:
        class: AppBundle\Services\UserSecurity
        arguments: [@security.encoder_factory]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
